-- Marcar lotes como concluídos (preenchendo data_recebimento_ri com data atual)
-- Nomes corrigidos conforme banco de dados

UPDATE registros SET data_recebimento_ri = CURRENT_DATE
WHERE lote_id IN (
  SELECT l.id FROM lotes l
  JOIN empreendimentos e ON l.empreendimento_id = e.id
  WHERE (e.nome, l.numero) IN (
    ('Parque Lorena l', '1'),
    ('Parque da Guarda Residence', '1'),
    ('Jardim do Parque', '1'),
    ('Parque Lorena II', '1'),
    ('Parque Lorena l', '2'),
    ('Parque da Guarda Residence', '2'),
    ('Jardim do Parque', '2'),
    ('Parque Lorena II', '2'),
    ('Algarve ', '2'),
    ('Aurora', '2'),
    ('Parque Lorena l', '3'),
    ('Parque da Guarda Residence', '3'),
    ('Jardim do Parque', '3'),
    ('Montecarlo', '3'),
    ('Parque Lorena II', '3'),
    ('Algarve ', '3'),
    ('Aurora', '3'),
    ('Parque Lorena l', '4'),
    ('Parque da Guarda Residence', '4'),
    ('Jardim do Parque', '4'),
    ('Montecarlo', '4'),
    ('Parque Lorena II', '4'),
    ('Parque Lorena l', '5'),
    ('Parque da Guarda Residence', '5'),
    ('Jardim do Parque', '5'),
    ('Montecarlo', '5'),
    ('Parque Lorena II', '5'),
    ('Algarve ', '5'),
    ('Parque Lorena l', '6'),
    ('Ilha dos Açores', '6'),
    ('Parque da Guarda Residence', '6'),
    ('Jardim do Parque', '6'),
    ('Parque Lorena II', '6'),
    ('Algarve ', '6'),
    ('Parque Lorena l', '7'),
    ('Ilha dos Açores', '7'),
    ('Parque da Guarda Residence', '7'),
    ('Jardim do Parque', '7'),
    ('Montecarlo', '7'),
    ('Parque Lorena II', '7'),
    ('Parque Lorena l', '8'),
    ('Ilha dos Açores', '8'),
    ('Parque da Guarda Residence', '8'),
    ('Jardim do Parque', '8'),
    ('Montecarlo', '8'),
    ('Parque Lorena II', '8'),
    ('Parque Lorena l', '9'),
    ('Ilha dos Açores', '9'),
    ('Parque da Guarda Residence', '9'),
    ('Jardim do Parque', '9'),
    ('Montecarlo', '9'),
    ('Parque Lorena II', '9'),
    ('Ilha dos Açores', '10'),
    ('Parque Lorena l', '10'),
    ('Parque da Guarda Residence', '10'),
    ('Jardim do Parque', '10'),
    ('Montecarlo', '10'),
    ('Parque Lorena II', '10'),
    ('Algarve ', '10'),
    ('Aurora', '10'),
    ('Ilha dos Açores', '11'),
    ('Parque Lorena l', '11'),
    ('Parque da Guarda Residence', '11'),
    ('Jardim do Parque', '11'),
    ('Parque Lorena II', '11'),
    ('Aurora', '11'),
    ('Parque Lorena l', '12'),
    ('Ilha dos Açores', '12'),
    ('Parque da Guarda Residence', '12'),
    ('Jardim do Parque', '12'),
    ('Montecarlo', '12'),
    ('Parque Lorena II', '12'),
    ('Parque Lorena l', '13'),
    ('Ilha dos Açores', '13'),
    ('Parque da Guarda Residence', '13'),
    ('Jardim do Parque', '13'),
    ('Montecarlo', '13'),
    ('Parque Lorena II', '13'),
    ('Parque Lorena l', '14'),
    ('Parque da Guarda Residence', '14'),
    ('Jardim do Parque', '14'),
    ('Montecarlo', '14'),
    ('Parque Lorena II', '14'),
    ('Algarve ', '14'),
    ('Ilha dos Açores', '15'),
    ('Parque Lorena l', '15'),
    ('Parque da Guarda Residence', '15'),
    ('Jardim do Parque', '15'),
    ('Montecarlo', '15'),
    ('Parque Lorena II', '15'),
    ('Parque Lorena l', '16'),
    ('Ilha dos Açores', '16'),
    ('Jardim do Parque', '16'),
    ('Montecarlo', '16'),
    ('Parque Lorena II', '16'),
    ('Ilha dos Açores', '17'),
    ('Parque Lorena l', '17'),
    ('Parque da Guarda Residence', '17'),
    ('Jardim do Parque', '17'),
    ('Parque Lorena II', '17'),
    ('Ilha dos Açores', '18'),
    ('Parque Lorena l', '18'),
    ('Parque da Guarda Residence', '18'),
    ('Jardim do Parque', '18'),
    ('Montecarlo', '18'),
    ('Parque Lorena II', '18'),
    ('Parque Lorena l', '19'),
    ('Ilha dos Açores', '19'),
    ('Parque da Guarda Residence', '19'),
    ('Jardim do Parque', '19'),
    ('Montecarlo', '19'),
    ('Parque Lorena II', '19'),
    ('Aurora', '19'),
    ('Ilha dos Açores', '20'),
    ('Parque Lorena l', '20'),
    ('Parque da Guarda Residence', '20'),
    ('Jardim do Parque', '20'),
    ('Montecarlo', '20'),
    ('Parque Lorena II', '20'),
    ('Aurora', '20'),
    ('Ilha dos Açores', '21'),
    ('Parque Lorena l', '21'),
    ('Parque da Guarda Residence', '21'),
    ('Jardim do Parque', '21'),
    ('Parque Lorena II', '21'),
    ('Ilha dos Açores', '22'),
    ('Parque Lorena l', '22'),
    ('Parque da Guarda Residence', '22'),
    ('Jardim do Parque', '22'),
    ('Montecarlo', '22'),
    ('Parque Lorena II', '22'),
    ('Ilha dos Açores', '23'),
    ('Parque Lorena l', '23'),
    ('Parque da Guarda Residence', '23'),
    ('Jardim do Parque', '23'),
    ('Montecarlo', '23'),
    ('Parque Lorena II', '23'),
    ('Ilha dos Açores', '24'),
    ('Parque Lorena l', '24'),
    ('Parque da Guarda Residence', '24'),
    ('Jardim do Parque', '24'),
    ('Montecarlo', '24'),
    ('Parque Lorena II', '24'),
    ('Algarve ', '24'),
    ('Ilha dos Açores', '25'),
    ('Parque da Guarda Residence', '25'),
    ('Jardim do Parque', '25'),
    ('Montecarlo', '25'),
    ('Parque Lorena II', '25'),
    ('Parque Lorena l', '26'),
    ('Ilha dos Açores', '26'),
    ('Parque da Guarda Residence', '26'),
    ('Jardim do Parque', '26'),
    ('Parque Lorena l', '27'),
    ('Ilha dos Açores', '27'),
    ('Parque da Guarda Residence', '27'),
    ('Jardim do Parque', '27'),
    ('Parque Lorena II', '27'),
    ('Aurora', '27'),
    ('Parque Lorena l', '28'),
    ('Ilha dos Açores', '28'),
    ('Parque da Guarda Residence', '28'),
    ('Jardim do Parque', '28'),
    ('Montecarlo', '28'),
    ('Parque Lorena II', '28'),
    ('Aurora', '28'),
    ('Ilha dos Açores', '29'),
    ('Montecarlo', '29'),
    ('Parque Lorena l', '29'),
    ('Parque da Guarda Residence', '29'),
    ('Jardim do Parque', '29'),
    ('Parque Lorena II', '29'),
    ('Ilha dos Açores', '30'),
    ('Parque Lorena l', '30'),
    ('Parque da Guarda Residence', '30'),
    ('Jardim do Parque', '30'),
    ('Algarve ', '30'),
    ('Ilha dos Açores', '31'),
    ('Parque Lorena l', '31'),
    ('Parque da Guarda Residence', '31'),
    ('Jardim do Parque', '31'),
    ('Parque Lorena II', '31'),
    ('Parque Lorena l', '32'),
    ('Parque da Guarda Residence', '32'),
    ('Montecarlo', '32'),
    ('Jardim do Parque', '32'),
    ('Aurora', '32'),
    ('Parque Lorena l', '33'),
    ('Ilha dos Açores', '33'),
    ('Parque da Guarda Residence', '33'),
    ('Jardim do Parque', '33'),
    ('Montecarlo', '33'),
    ('Ilha dos Açores', '34'),
    ('Parque Lorena l', '34'),
    ('Parque da Guarda Residence', '34'),
    ('Jardim do Parque', '34'),
    ('Montecarlo', '34'),
    ('Aurora', '34'),
    ('Ilha dos Açores', '35'),
    ('Parque Lorena l', '35'),
    ('Parque da Guarda Residence', '35'),
    ('Jardim do Parque', '35'),
    ('Montecarlo', '35'),
    ('Parque Lorena II', '35'),
    ('Aurora', '35'),
    ('Ilha dos Açores', '36'),
    ('Parque Lorena l', '36'),
    ('Jardim do Parque', '36'),
    ('Parque Lorena II', '36'),
    ('Parque Lorena l', '37'),
    ('Ilha dos Açores', '37'),
    ('Parque da Guarda Residence', '37'),
    ('Jardim do Parque', '37'),
    ('Montecarlo', '37'),
    ('Parque Lorena II', '37'),
    ('Parque Lorena l', '38'),
    ('Ilha dos Açores', '38'),
    ('Parque da Guarda Residence', '38'),
    ('Jardim do Parque', '38'),
    ('Montecarlo', '38'),
    ('Parque Lorena II', '38'),
    ('Ilha dos Açores', '39'),
    ('Parque Lorena l', '39'),
    ('Parque da Guarda Residence', '39'),
    ('Jardim do Parque', '39'),
    ('Parque Lorena II', '39'),
    ('Ilha dos Açores', '40'),
    ('Parque Lorena l', '40'),
    ('Parque da Guarda Residence', '40'),
    ('Jardim do Parque', '40'),
    ('Montecarlo', '40'),
    ('Parque Lorena II', '40'),
    ('Ilha dos Açores', '41'),
    ('Parque Lorena l', '41'),
    ('Parque da Guarda Residence', '41'),
    ('Jardim do Parque', '41'),
    ('Ilha dos Açores', '42'),
    ('Parque da Guarda Residence', '42'),
    ('Parque Lorena l', '42'),
    ('Jardim do Parque', '42'),
    ('Montecarlo', '42'),
    ('Parque Lorena II', '42'),
    ('Parque Lorena l', '43'),
    ('Ilha dos Açores', '43'),
    ('Parque da Guarda Residence', '43'),
    ('Jardim do Parque', '43'),
    ('Montecarlo', '43'),
    ('Parque Lorena II', '43'),
    ('Parque Lorena l', '44'),
    ('Ilha dos Açores', '44'),
    ('Parque da Guarda Residence', '44'),
    ('Jardim do Parque', '44'),
    ('Montecarlo', '44'),
    ('Parque Lorena II', '44'),
    ('Jardim do Parque', '45'),
    ('Parque Lorena l', '45'),
    ('Ilha dos Açores', '45'),
    ('Parque da Guarda Residence', '45'),
    ('Montecarlo', '45'),
    ('Parque Lorena II', '45'),
    ('Ilha dos Açores', '46'),
    ('Parque Lorena l', '46'),
    ('Parque da Guarda Residence', '46'),
    ('Jardim do Parque', '46'),
    ('Parque Lorena II', '46'),
    ('Ilha dos Açores', '47'),
    ('Parque Lorena l', '47'),
    ('Parque da Guarda Residence', '47'),
    ('Jardim do Parque', '47'),
    ('Montecarlo', '47'),
    ('Parque Lorena II', '47'),
    ('Algarve ', '47'),
    ('Ilha dos Açores', '48'),
    ('Parque Lorena l', '48'),
    ('Parque da Guarda Residence', '48'),
    ('Jardim do Parque', '48'),
    ('Montecarlo', '48'),
    ('Parque Lorena II', '48'),
    ('Algarve ', '48'),
    ('Ilha dos Açores', '49'),
    ('Parque Lorena l', '49'),
    ('Parque da Guarda Residence', '49'),
    ('Jardim do Parque', '49'),
    ('Montecarlo', '49'),
    ('Parque Lorena II', '49'),
    ('Parque Lorena l', '50'),
    ('Ilha dos Açores', '50'),
    ('Parque da Guarda Residence', '50'),
    ('Jardim do Parque', '50'),
    ('Montecarlo', '50'),
    ('Parque Lorena II', '50'),
    ('Ilha dos Açores', '51'),
    ('Jardim do Parque', '51'),
    ('Parque Lorena l', '51'),
    ('Parque da Guarda Residence', '51'),
    ('Parque Lorena II', '51'),
    ('Ilha dos Açores', '52'),
    ('Parque Lorena l', '52'),
    ('Parque da Guarda Residence', '52'),
    ('Jardim do Parque', '52'),
    ('Montecarlo', '52'),
    ('Parque Lorena II', '52'),
    ('Ilha dos Açores', '53'),
    ('Parque Lorena l', '53'),
    ('Jardim do Parque', '53'),
    ('Montecarlo', '53'),
    ('Parque Lorena II', '53'),
    ('Parque Lorena l', '54'),
    ('Ilha dos Açores', '54'),
    ('Jardim do Parque', '54'),
    ('Montecarlo', '54'),
    ('Parque Lorena II', '54'),
    ('Parque Lorena l', '55'),
    ('Jardim do Parque', '55'),
    ('Montecarlo', '55'),
    ('Parque Lorena II', '55'),
    ('Ilha dos Açores', '56'),
    ('Parque Lorena l', '56'),
    ('Jardim do Parque', '56'),
    ('Parque Lorena II', '56'),
    ('Ilha dos Açores', '57'),
    ('Parque Lorena l', '57'),
    ('Jardim do Parque', '57'),
    ('Montecarlo', '57'),
    ('Parque Lorena II', '57'),
    ('Aurora', '57'),
    ('Parque Lorena l', '58'),
    ('Jardim do Parque', '58'),
    ('Montecarlo', '58'),
    ('Parque Lorena II', '58'),
    ('Aurora', '58'),
    ('Parque Lorena l', '59'),
    ('Ilha dos Açores', '59'),
    ('Jardim do Parque', '59'),
    ('Montecarlo', '59'),
    ('Parque Lorena II', '59'),
    ('Aurora', '59'),
    ('Montecarlo', '60'),
    ('Parque Lorena l', '60'),
    ('Ilha dos Açores', '60'),
    ('Jardim do Parque', '60'),
    ('Parque Lorena II', '60'),
    ('Aurora', '60'),
    ('Parque Lorena l', '61'),
    ('Ilha dos Açores', '61'),
    ('Jardim do Parque', '61'),
    ('Aurora', '61'),
    ('Ilha dos Açores', '62'),
    ('Parque Lorena l', '62'),
    ('Jardim do Parque', '62'),
    ('Montecarlo', '62'),
    ('Parque Lorena II', '62'),
    ('Aurora', '62'),
    ('Parque Lorena l', '63'),
    ('Jardim do Parque', '63'),
    ('Montecarlo', '63'),
    ('Parque Lorena II', '63'),
    ('Parque Lorena l', '64'),
    ('Ilha dos Açores', '64'),
    ('Jardim do Parque', '64'),
    ('Montecarlo', '64'),
    ('Parque Lorena II', '64'),
    ('Aurora', '64'),
    ('Ilha dos Açores', '65'),
    ('Parque Lorena l', '65'),
    ('Jardim do Parque', '65'),
    ('Montecarlo', '65'),
    ('Aurora', '65'),
    ('Parque Lorena l', '66'),
    ('Ilha dos Açores', '66'),
    ('Jardim do Parque', '66'),
    ('Parque Lorena II', '66'),
    ('Algarve ', '66'),
    ('Aurora', '66'),
    ('Ilha dos Açores', '67'),
    ('Parque Lorena l', '67'),
    ('Jardim do Parque', '67'),
    ('Parque Lorena II', '67'),
    ('Algarve ', '67'),
    ('Aurora', '67'),
    ('Ilha dos Açores', '68'),
    ('Jardim do Parque', '68'),
    ('Montecarlo', '68'),
    ('Parque Lorena II', '68'),
    ('Parque Lorena l', '69'),
    ('Jardim do Parque', '69'),
    ('Montecarlo', '69'),
    ('Parque Lorena II', '69'),
    ('Algarve ', '69'),
    ('Parque Lorena l', '70'),
    ('Ilha dos Açores', '70'),
    ('Jardim do Parque', '70'),
    ('Montecarlo', '70'),
    ('Parque Lorena II', '70'),
    ('Parque Lorena l', '71'),
    ('Ilha dos Açores', '71'),
    ('Jardim do Parque', '71'),
    ('Parque Lorena II', '71'),
    ('Algarve ', '71'),
    ('Ilha dos Açores', '72'),
    ('Parque Lorena l', '72'),
    ('Jardim do Parque', '72'),
    ('Parque Lorena II', '72'),
    ('Algarve ', '72'),
    ('Aurora', '72'),
    ('Erico Verissimo ', '72'),
    ('Parque Lorena l', '73'),
    ('Ilha dos Açores', '73'),
    ('Jardim do Parque', '73'),
    ('Montecarlo', '73'),
    ('Parque Lorena II', '73'),
    ('Algarve ', '73'),
    ('Aurora', '73'),
    ('Parque Lorena l', '74'),
    ('Ilha dos Açores', '74'),
    ('Jardim do Parque', '74'),
    ('Montecarlo', '74'),
    ('Parque Lorena II', '74'),
    ('Aurora', '74'),
    ('Parque Lorena l', '75'),
    ('Ilha dos Açores', '75'),
    ('Jardim do Parque', '75'),
    ('Parque Lorena II', '75'),
    ('Algarve ', '75'),
    ('Aurora', '75'),
    ('Ilha dos Açores', '76'),
    ('Parque Lorena l', '76'),
    ('Jardim do Parque', '76'),
    ('Montecarlo', '76'),
    ('Parque Lorena II', '76'),
    ('Algarve ', '76'),
    ('Parque Lorena l', '77'),
    ('Ilha dos Açores', '77'),
    ('Jardim do Parque', '77'),
    ('Montecarlo', '77'),
    ('Parque Lorena II', '77'),
    ('Ilha dos Açores', '78'),
    ('Parque Lorena l', '78'),
    ('Jardim do Parque', '78'),
    ('Montecarlo', '78'),
    ('Parque Lorena II', '78'),
    ('Parque Lorena l', '79'),
    ('Ilha dos Açores', '79'),
    ('Jardim do Parque', '79'),
    ('Montecarlo', '79'),
    ('Parque Lorena II', '79'),
    ('Algarve ', '79'),
    ('Ilha dos Açores', '80'),
    ('Parque Lorena l', '80'),
    ('Jardim do Parque', '80'),
    ('Montecarlo', '80'),
    ('Parque Lorena II', '80'),
    ('Algarve ', '80'),
    ('Aurora', '80'),
    ('Ilha dos Açores', '81'),
    ('Jardim do Parque', '81'),
    ('Parque Lorena l', '81'),
    ('Parque Lorena II', '81'),
    ('Algarve ', '81'),
    ('Ilha dos Açores', '82'),
    ('Jardim do Parque', '82'),
    ('Montecarlo', '82'),
    ('Parque Lorena l', '82'),
    ('Parque Lorena II', '82'),
    ('Algarve ', '82'),
    ('Ilha dos Açores', '83'),
    ('Jardim do Parque', '83'),
    ('Parque Lorena l', '83'),
    ('Montecarlo', '83'),
    ('Parque Lorena II', '83'),
    ('Ilha dos Açores', '84'),
    ('Parque Lorena l', '84'),
    ('Jardim do Parque', '84'),
    ('Montecarlo', '84'),
    ('Parque Lorena II', '84'),
    ('Ilha dos Açores', '85'),
    ('Parque Lorena l', '85'),
    ('Jardim do Parque', '85'),
    ('Montecarlo', '85'),
    ('Parque Lorena II', '85'),
    ('Ilha dos Açores', '86'),
    ('Parque Lorena l', '86'),
    ('Parque Lorena II', '86'),
    ('Ilha dos Açores', '87'),
    ('Parque Lorena l', '87'),
    ('Montecarlo', '87'),
    ('Ilha dos Açores', '88'),
    ('Montecarlo', '88'),
    ('Erico Verissimo ', '88'),
    ('Ilha dos Açores', '89'),
    ('Parque Lorena l', '89'),
    ('Montecarlo', '89'),
    ('Parque Lorena II', '89'),
    ('Erico Verissimo ', '89'),
    ('Ilha dos Açores', '90'),
    ('Parque Lorena l', '90'),
    ('Montecarlo', '90'),
    ('Parque Lorena II', '90'),
    ('Erico Verissimo ', '90'),
    ('Parque Lorena l', '91'),
    ('Ilha dos Açores', '91'),
    ('Parque Lorena II', '91'),
    ('Ilha dos Açores', '92'),
    ('Parque Lorena l', '92'),
    ('Montecarlo', '92'),
    ('Parque Lorena II', '92'),
    ('Aurora', '92'),
    ('Ilha dos Açores', '93'),
    ('Parque Lorena l', '93'),
    ('Parque Lorena II', '93'),
    ('Aurora', '93'),
    ('Ilha dos Açores', '94'),
    ('Parque Lorena l', '94'),
    ('Montecarlo', '94'),
    ('Parque Lorena II', '94'),
    ('Aurora', '94'),
    ('Parque Lorena l', '95'),
    ('Ilha dos Açores', '95'),
    ('Montecarlo', '95'),
    ('Parque Lorena II', '95'),
    ('Aurora', '95'),
    ('Parque Lorena l', '96'),
    ('Ilha dos Açores', '96'),
    ('Parque Lorena II', '96'),
    ('Aurora', '96'),
    ('Parque Lorena l', '97'),
    ('Ilha dos Açores', '97'),
    ('Montecarlo', '97'),
    ('Parque Lorena II', '97'),
    ('Aurora', '97'),
    ('Parque Lorena l', '98'),
    ('Ilha dos Açores', '98'),
    ('Montecarlo', '98'),
    ('Parque Lorena II', '98'),
    ('Parque Lorena l', '99'),
    ('Ilha dos Açores', '99'),
    ('Montecarlo', '99'),
    ('Parque Lorena l', '100'),
    ('Ilha dos Açores', '100'),
    ('Montecarlo', '100'),
    ('Ilha dos Açores', '101'),
    ('Parque Lorena l', '101'),
    ('Parque Lorena II', '101'),
    ('Ilha dos Açores', '102'),
    ('Parque Lorena l', '102'),
    ('Montecarlo', '102'),
    ('Parque Lorena II', '102'),
    ('Aurora', '102'),
    ('Ilha dos Açores', '103'),
    ('Parque Lorena l', '103'),
    ('Montecarlo', '103'),
    ('Aurora', '103'),
    ('Ilha dos Açores', '104'),
    ('Parque Lorena l', '104'),
    ('Montecarlo', '104'),
    ('Parque Lorena II', '104'),
    ('Aurora', '104'),
    ('Parque Lorena l', '105'),
    ('Ilha dos Açores', '105'),
    ('Montecarlo', '105'),
    ('Parque Lorena II', '105'),
    ('Ilha dos Açores', '106'),
    ('Parque Lorena l', '106'),
    ('Parque Lorena II', '106'),
    ('Aurora', '106'),
    ('Parque Lorena l', '107'),
    ('Ilha dos Açores', '107'),
    ('Montecarlo', '107'),
    ('Parque Lorena II', '107'),
    ('Parque Lorena l', '108'),
    ('Ilha dos Açores', '108'),
    ('Montecarlo', '108'),
    ('Parque Lorena II', '108'),
    ('Parque Lorena l', '109'),
    ('Ilha dos Açores', '109'),
    ('Montecarlo', '109'),
    ('Parque Lorena II', '109'),
    ('Aurora', '109'),
    ('Parque Lorena l', '110'),
    ('Ilha dos Açores', '110'),
    ('Montecarlo', '110'),
    ('Parque Lorena II', '110'),
    ('Aurora', '110'),
    ('Ilha dos Açores', '111'),
    ('Parque Lorena l', '111'),
    ('Parque Lorena II', '111'),
    ('Aurora', '111'),
    ('Ilha dos Açores', '112'),
    ('Parque Lorena l', '112'),
    ('Montecarlo', '112'),
    ('Parque Lorena II', '112'),
    ('Ilha dos Açores', '113'),
    ('Parque Lorena l', '113'),
    ('Montecarlo', '113'),
    ('Parque Lorena l', '114'),
    ('Ilha dos Açores', '114'),
    ('Montecarlo', '114'),
    ('Parque Lorena II', '114'),
    ('Parque Lorena l', '115'),
    ('Ilha dos Açores', '115'),
    ('Montecarlo', '115'),
    ('Parque Lorena II', '115'),
    ('Ilha dos Açores', '116'),
    ('Parque Lorena II', '116'),
    ('Ilha dos Açores', '117'),
    ('Montecarlo', '117'),
    ('Parque Lorena l', '117'),
    ('Parque Lorena l', '118'),
    ('Ilha dos Açores', '118'),
    ('Montecarlo', '118'),
    ('Parque Lorena II', '118'),
    ('Parque Lorena l', '119'),
    ('Ilha dos Açores', '119'),
    ('Montecarlo', '119'),
    ('Parque Lorena II', '119'),
    ('Aurora', '119'),
    ('Ilha dos Açores', '120'),
    ('Parque Lorena l', '120'),
    ('Montecarlo', '120'),
    ('Parque Lorena II', '120'),
    ('Aurora', '120'),
    ('Ilha dos Açores', '121'),
    ('Parque Lorena l', '121'),
    ('Parque Lorena II', '121'),
    ('Parque Lorena l', '122'),
    ('Ilha dos Açores', '122'),
    ('Montecarlo', '122'),
    ('Parque Lorena II', '122'),
    ('Parque Lorena l', '123'),
    ('Ilha dos Açores', '123'),
    ('Montecarlo', '123'),
    ('Parque Lorena II', '123'),
    ('Aurora', '123'),
    ('Ilha dos Açores', '124'),
    ('Parque Lorena l', '124'),
    ('Parque Lorena II', '124'),
    ('Aurora', '124'),
    ('Ilha dos Açores', '125'),
    ('Parque Lorena l', '125'),
    ('Parque Lorena II', '125'),
    ('Parque Lorena l', '126'),
    ('Ilha dos Açores', '126'),
    ('Aurora', '126'),
    ('Ilha dos Açores', '127'),
    ('Parque Lorena l', '127'),
    ('Montecarlo', '127'),
    ('Aurora', '127'),
    ('Ilha dos Açores', '128'),
    ('Parque Lorena l', '128'),
    ('Montecarlo', '128'),
    ('Aurora', '128'),
    ('Morada da Coxilha ', '128'),
    ('Ilha dos Açores', '129'),
    ('Parque Lorena l', '129'),
    ('Montecarlo', '129'),
    ('Aurora', '129'),
    ('Ilha dos Açores', '130'),
    ('Parque Lorena l', '130'),
    ('Montecarlo', '130'),
    ('Aurora', '130'),
    ('Parque Lorena l', '131'),
    ('Parque Lorena l', '132'),
    ('Montecarlo', '132'),
    ('Aurora', '132'),
    ('Parque Lorena l', '133'),
    ('Ilha dos Açores', '133'),
    ('Montecarlo', '133'),
    ('Ilha dos Açores', '134'),
    ('Parque Lorena l', '134'),
    ('Montecarlo', '134'),
    ('Aurora', '134'),
    ('Ilha dos Açores', '135'),
    ('Parque Lorena l', '135'),
    ('Montecarlo', '135'),
    ('Aurora', '135'),
    ('Ilha dos Açores', '136'),
    ('Parque Lorena l', '136'),
    ('Parque Lorena l', '137'),
    ('Montecarlo', '137'),
    ('Aurora', '137'),
    ('Ilha dos Açores', '138'),
    ('Parque Lorena l', '138'),
    ('Montecarlo', '138'),
    ('Aurora', '138'),
    ('Ilha dos Açores', '139'),
    ('Parque Lorena l', '139'),
    ('Montecarlo', '139'),
    ('Aurora', '139'),
    ('Parque Lorena l', '140'),
    ('Montecarlo', '140'),
    ('Ilha dos Açores', '141'),
    ('Parque Lorena l', '141'),
    ('Aurora', '141'),
    ('Parque Lorena l', '142'),
    ('Ilha dos Açores', '142'),
    ('Montecarlo', '142'),
    ('Ilha dos Açores', '143'),
    ('Parque Lorena l', '143'),
    ('Montecarlo', '143'),
    ('Ilha dos Açores', '144'),
    ('Parque Lorena l', '144'),
    ('Montecarlo', '144'),
    ('Ilha dos Açores', '145'),
    ('Parque Lorena l', '145'),
    ('Montecarlo', '145'),
    ('Parque Lorena l', '146'),
    ('Ilha dos Açores', '146'),
    ('Montecarlo', '147'),
    ('Parque Lorena l', '147'),
    ('Ilha dos Açores', '147'),
    ('Parque Lorena l', '148'),
    ('Ilha dos Açores', '148'),
    ('Montecarlo', '148'),
    ('Parque Lorena l', '149'),
    ('Montecarlo', '149'),
    ('Ilha dos Açores', '150'),
    ('Parque Lorena l', '150'),
    ('Montecarlo', '150'),
    ('Aurora', '150'),
    ('Ilha dos Açores', '151'),
    ('Parque Lorena l', '151'),
    ('Aurora', '151'),
    ('Ilha dos Açores', '152'),
    ('Parque Lorena l', '152'),
    ('Montecarlo', '152'),
    ('Ilha dos Açores', '153'),
    ('Parque Lorena l', '153'),
    ('Montecarlo', '153'),
    ('Parque Lorena l', '154'),
    ('Montecarlo', '154'),
    ('Ilha dos Açores', '155'),
    ('Parque Lorena l', '155'),
    ('Montecarlo', '155'),
    ('Parque Lorena l', '156'),
    ('Ilha dos Açores', '156'),
    ('Aurora', '156'),
    ('Ilha dos Açores', '157'),
    ('Parque Lorena l', '157'),
    ('Montecarlo', '157'),
    ('Aurora', '157'),
    ('Ilha dos Açores', '158'),
    ('Parque Lorena l', '158'),
    ('Montecarlo', '158'),
    ('Aurora', '158'),
    ('Ilha dos Açores', '159'),
    ('Parque Lorena l', '159'),
    ('Montecarlo', '159'),
    ('Ilha dos Açores', '160'),
    ('Parque Lorena l', '160'),
    ('Montecarlo', '160'),
    ('Ilha dos Açores', '161'),
    ('Parque Lorena l', '161'),
    ('Ilha dos Açores', '162'),
    ('Parque Lorena l', '162'),
    ('Montecarlo', '162'),
    ('Ilha dos Açores', '163'),
    ('Parque Lorena l', '163'),
    ('Montecarlo', '163'),
    ('Ilha dos Açores', '164'),
    ('Parque Lorena l', '164'),
    ('Montecarlo', '164'),
    ('Aurora', '164'),
    ('Ilha dos Açores', '165'),
    ('Parque Lorena l', '165'),
    ('Aurora', '165'),
    ('Ilha dos Açores', '166'),
    ('Parque Lorena l', '166'),
    ('Montecarlo', '166'),
    ('Ilha dos Açores', '167'),
    ('Parque Lorena l', '167'),
    ('Montecarlo', '167'),
    ('Ilha dos Açores', '168'),
    ('Montecarlo', '168'),
    ('Aurora', '168'),
    ('Ilha dos Açores', '169'),
    ('Parque Lorena l', '169'),
    ('Montecarlo', '169'),
    ('Aurora', '169'),
    ('Ilha dos Açores', '170'),
    ('Parque Lorena l', '170'),
    ('Montecarlo', '170'),
    ('Aurora', '170'),
    ('Ilha dos Açores', '171'),
    ('Parque Lorena l', '171'),
    ('Aurora', '171'),
    ('Ilha dos Açores', '172'),
    ('Montecarlo', '172'),
    ('Aurora', '172'),
    ('Ilha dos Açores', '173'),
    ('Ilha dos Açores', '174'),
    ('Montecarlo', '174'),
    ('Aurora', '174'),
    ('Ilha dos Açores', '175'),
    ('Montecarlo', '175'),
    ('Aurora', '175'),
    ('Aurora', '176'),
    ('Ilha dos Açores', '177'),
    ('Montecarlo', '177'),
    ('Aurora', '177'),
    ('Ilha dos Açores', '178'),
    ('Montecarlo', '178'),
    ('Ilha dos Açores', '179'),
    ('Montecarlo', '179'),
    ('Aurora', '179'),
    ('Ilha dos Açores', '180'),
    ('Montecarlo', '180'),
    ('Aurora', '180'),
    ('Ilha dos Açores', '181'),
    ('Aurora', '181'),
    ('Ilha dos Açores', '182'),
    ('Montecarlo', '182'),
    ('Ilha dos Açores', '183'),
    ('Montecarlo', '187'),
    ('Montecarlo', '188'),
    ('Montecarlo', '189'),
    ('Montecarlo', '190'),
    ('Ilha dos Açores', '191'),
    ('Aurora', '191'),
    ('Ilha dos Açores', '192'),
    ('Montecarlo', '192'),
    ('Ilha dos Açores', '193'),
    ('Montecarlo', '193'),
    ('Ilha dos Açores', '194'),
    ('Montecarlo', '194'),
    ('Aurora', '194'),
    ('Ilha dos Açores', '195'),
    ('Montecarlo', '195'),
    ('Aurora', '195'),
    ('Ilha dos Açores', '196'),
    ('Ilha dos Açores', '197'),
    ('Montecarlo', '197'),
    ('Ilha dos Açores', '198'),
    ('Ilha dos Açores', '199'),
    ('Montecarlo', '199'),
    ('Montecarlo', '200'),
    ('Ilha dos Açores', '201'),
    ('Aurora', '201'),
    ('Ilha dos Açores', '202'),
    ('Montecarlo', '202'),
    ('Aurora', '202'),
    ('Ilha dos Açores', '203'),
    ('Montecarlo', '203'),
    ('Ilha dos Açores', '204'),
    ('Montecarlo', '204'),
    ('Ilha dos Açores', '205'),
    ('Montecarlo', '205'),
    ('Ilha dos Açores', '206'),
    ('Montecarlo', '207'),
    ('Montecarlo', '208'),
    ('Montecarlo', '209'),
    ('Aurora', '209'),
    ('Ilha dos Açores', '210'),
    ('Montecarlo', '210'),
    ('Aurora', '210'),
    ('Ilha dos Açores', '211'),
    ('Aurora', '211'),
    ('Erico Verissimo ', '211'),
    ('Ilha dos Açores', '212'),
    ('Montecarlo', '212'),
    ('Ilha dos Açores', '213'),
    ('Montecarlo', '213'),
    ('Ilha dos Açores', '214'),
    ('Montecarlo', '214'),
    ('Ilha dos Açores', '215'),
    ('Montecarlo', '215'),
    ('Aurora', '215'),
    ('Ilha dos Açores', '216'),
    ('Aurora', '216'),
    ('Ilha dos Açores', '217'),
    ('Montecarlo', '217'),
    ('Aurora', '217'),
    ('Ilha dos Açores', '218'),
    ('Montecarlo', '218'),
    ('Ilha dos Açores', '219'),
    ('Ilha dos Açores', '220'),
    ('Montecarlo', '220'),
    ('Aurora', '220'),
    ('Montecarlo', '221'),
    ('Ilha dos Açores', '222'),
    ('Montecarlo', '222'),
    ('Ilha dos Açores', '223'),
    ('Montecarlo', '223'),
    ('Aurora', '223'),
    ('Ilha dos Açores', '224'),
    ('Montecarlo', '224'),
    ('Aurora', '224'),
    ('Ilha dos Açores', '225'),
    ('Montecarlo', '225'),
    ('Aurora', '226'),
    ('Montecarlo', '227'),
    ('Aurora', '227'),
    ('Ilha dos Açores', '228'),
    ('Montecarlo', '228'),
    ('Ilha dos Açores', '229'),
    ('Montecarlo', '229'),
    ('Ilha dos Açores', '230'),
    ('Montecarlo', '230'),
    ('Erico Verissimo ', '230'),
    ('Ilha dos Açores', '231'),
    ('Montecarlo', '232'),
    ('Ilha dos Açores', '233'),
    ('Montecarlo', '233'),
    ('Montecarlo', '234'),
    ('Ilha dos Açores', '235'),
    ('Montecarlo', '235'),
    ('Ilha dos Açores', '236'),
    ('Ilha dos Açores', '237'),
    ('Montecarlo', '237'),
    ('Ilha dos Açores', '238'),
    ('Montecarlo', '238'),
    ('Ilha dos Açores', '239'),
    ('Montecarlo', '239'),
    ('Ilha dos Açores', '240'),
    ('Ilha dos Açores', '241'),
    ('Montecarlo', '241'),
    ('Montecarlo', '242'),
    ('Aurora', '242'),
    ('Ilha dos Açores', '243'),
    ('Montecarlo', '243'),
    ('Aurora', '243'),
    ('Ilha dos Açores', '244'),
    ('Montecarlo', '244'),
    ('Ilha dos Açores', '245'),
    ('Montecarlo', '245'),
    ('Aurora', '245'),
    ('Ilha dos Açores', '246'),
    ('Aurora', '246'),
    ('Ilha dos Açores', '247'),
    ('Montecarlo', '247'),
    ('Aurora', '247'),
    ('Ilha dos Açores', '248'),
    ('Aurora', '249'),
    ('Ilha dos Açores', '250'),
    ('Montecarlo', '250'),
    ('Aurora', '250'),
    ('Ilha dos Açores', '251'),
    ('Ilha dos Açores', '252'),
    ('Montecarlo', '252'),
    ('Montecarlo', '253'),
    ('Ilha dos Açores', '254'),
    ('Montecarlo', '254'),
    ('Aurora', '254'),
    ('Ilha dos Açores', '255'),
    ('Montecarlo', '255'),
    ('Aurora', '255'),
    ('Ilha dos Açores', '256'),
    ('Aurora', '256'),
    ('Ilha dos Açores', '257'),
    ('Montecarlo', '257'),
    ('Aurora', '257'),
    ('Ilha dos Açores', '258'),
    ('Montecarlo', '258'),
    ('Ilha dos Açores', '259'),
    ('Aurora', '259'),
    ('Ilha dos Açores', '260'),
    ('Montecarlo', '260'),
    ('Ilha dos Açores', '261'),
    ('Aurora', '261'),
    ('Ilha dos Açores', '262'),
    ('Aurora', '262'),
    ('Ilha dos Açores', '263'),
    ('Aurora', '263'),
    ('Aurora', '264'),
    ('Ilha dos Açores', '265'),
    ('Aurora', '265'),
    ('Ilha dos Açores', '266'),
    ('Aurora', '266'),
    ('Ilha dos Açores', '267'),
    ('Ilha dos Açores', '268'),
    ('Aurora', '268'),
    ('Aurora', '269'),
    ('Aurora', '270'),
    ('Ilha dos Açores', '271'),
    ('Aurora', '271'),
    ('Ilha dos Açores', '272'),
    ('Aurora', '274'),
    ('Aurora', '275'),
    ('Aurora', '276'),
    ('Aurora', '277'),
    ('Aurora', '278'),
    ('Morada da Coxilha ', '278'),
    ('Ilha dos Açores', '279'),
    ('Aurora', '279'),
    ('Ilha dos Açores', '280'),
    ('Ilha dos Açores', '281'),
    ('Aurora', '281'),
    ('Ilha dos Açores', '282'),
    ('Aurora', '282'),
    ('Ilha dos Açores', '283'),
    ('Aurora', '283'),
    ('Ilha dos Açores', '284'),
    ('Ilha dos Açores', '285'),
    ('Aurora', '285'),
    ('Ilha dos Açores', '286'),
    ('Aurora', '286'),
    ('Ilha dos Açores', '287'),
    ('Aurora', '287'),
    ('Ilha dos Açores', '288'),
    ('Aurora', '288'),
    ('Ilha dos Açores', '289'),
    ('Ilha dos Açores', '290'),
    ('Aurora', '290'),
    ('Ilha dos Açores', '291'),
    ('Aurora', '291'),
    ('Ilha dos Açores', '292'),
    ('Ilha dos Açores', '293'),
    ('Ilha dos Açores', '294'),
    ('Aurora', '294'),
    ('Ilha dos Açores', '295'),
    ('Aurora', '295'),
    ('Ilha dos Açores', '296'),
    ('Aurora', '296'),
    ('Ilha dos Açores', '297'),
    ('Aurora', '297'),
    ('Ilha dos Açores', '298'),
    ('Aurora', '298'),
    ('Aurora', '299'),
    ('Ilha dos Açores', '301'),
    ('Aurora', '301'),
    ('Aurora', '302'),
    ('Ilha dos Açores', '303'),
    ('Ilha dos Açores', '307'),
    ('Ilha dos Açores', '309'),
    ('Ilha dos Açores', '310'),
    ('Ilha dos Açores', '311'),
    ('Ilha dos Açores', '312'),
    ('Ilha dos Açores', '313'),
    ('Ilha dos Açores', '314'),
    ('Ilha dos Açores', '316'),
    ('Ilha dos Açores', '317'),
    ('Ilha dos Açores', '318'),
    ('Ilha dos Açores', '319'),
    ('Ilha dos Açores', '321'),
    ('Ilha dos Açores', '322'),
    ('Ilha dos Açores', '324'),
    ('Ilha dos Açores', '325'),
    ('Ilha dos Açores', '326'),
    ('Ilha dos Açores', '327'),
    ('Ilha dos Açores', '328'),
    ('Ilha dos Açores', '329'),
    ('Ilha dos Açores', '330'),
    ('Ilha dos Açores', '332'),
    ('Ilha dos Açores', '333'),
    ('Ilha dos Açores', '334'),
    ('Ilha dos Açores', '336'),
    ('Ilha dos Açores', '337'),
    ('Ilha dos Açores', '338'),
    ('Ilha dos Açores', '339'),
    ('Ilha dos Açores', '340'),
    ('Ilha dos Açores', '341'),
    ('Ilha dos Açores', '342'),
    ('Ilha dos Açores', '343'),
    ('Ilha dos Açores', '344'),
    ('Ilha dos Açores', '345'),
    ('Ilha dos Açores', '346'),
    ('Ilha dos Açores', '347'),
    ('Ilha dos Açores', '348'),
    ('Ilha dos Açores', '350'),
    ('Ilha dos Açores', '351'),
    ('Ilha dos Açores', '352'),
    ('Ilha dos Açores', '354'),
    ('Ilha dos Açores', '356')
  )
);
